config/routes.rb
Cssa::Application.routes.draw do

  devise_for :users
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  root to: 'home#home'

  resources :blogs

end

app/models/blog.rb
class Blog < ActiveRecord::Base
	has_attached_file :logo, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"

	scope :college, -> {where(:category=>0)}
	scope :major, -> {where(:category=>1)}
	scope :transportation, -> {where(:category=>2)}
	scope :qa, -> {where(:category=>3)}
	scope :guide, -> {where(:category=>4)}
	scope :transferc, -> {where(:category=>5)}
	scope :transferg, -> {where(:category=>6)}
	scope :sdcc, -> {where(:category=>7)}
	scope :tip, -> {where(:category=>8)}
	scope :website, -> {where(:category=>9)}
	scope :library, -> {where(:category=>10)}
	scope :consult, -> {where(:category=>11)}
	scope :club, -> {where(:category=>12)}
	scope :job, -> {where(:category=>13)}
	scope :research, -> {where(:category=>14)}
	scope :abroad, -> {where(:category=>15)}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
  	@blog = Blog.where(:category=>params[:category])
  	if @blog.count == 1
  		@blog = @blog.first
  		render 'show'
  	end
  end

  def show
  	@blog ||= Blog.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/blogs/index.html.erb
<%= link_to "Home", root_path %>
<br>
<% @blog.each do |b| %>
  <%= link_to blog_path(b) do %>
    <% b.title %>
  <% end %>
  <br>
<% end %>

app/views/blogs/show.html.erb
<!--<div class="image-container">
  <div style="background-image: url(<%= @blog.logo.url%>)" class="blog-img">
  </div>
</div>-->


<div class="container">
	<div class="row title-author">
		<div class="col-lg-10 col-md-10 col-lg-offset-2 col-md-offset-2 blog-title">
			<%= @blog.title %>
	  </div>
	  <div class="col-lg-10 col-md-10 col-lg-offset-2 col-md-offset-2 blog-author">
			<%= @blog.author %>
	  </div>
	</div>
  <div class="row content-container">
  	<div class="col-lg-8 col-md-8 col-lg-offset-2 col-md-offset-2 blog-content">
      <%= simple_format(@blog.content) %>
      <%= image_tag @blog.logo.url %>
    </div>
  </div>
</div>

app/views/home/home.html.erb
 

<%= link_to "Colleges", blogs_path(:category=>0) %>

<%= link_to "For Freshmen", blogs_path(:category=>3) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cssa</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>